title: My first blog
author: Ayush Garg
email: 987ayush@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In this blog, I am going to talk about Web-development. I will talk about both front-end and back-end development.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-merlot
